
window.NIHONGO_DATA = (() => {
  const HIRAGANA = [
    ["あ","a"],["い","i"],["う","u"],["え","e"],["お","o"],["か","ka"],["き","ki"],["く","ku"],["け","ke"],["こ","ko"],
    ["さ","sa"],["し","shi"],["す","su"],["せ","se"],["そ","so"],["た","ta"],["ち","chi"],["つ","tsu"],["て","te"],["と","to"],
    ["な","na"],["に","ni"],["ぬ","nu"],["ね","ne"],["の","no"],["は","ha"],["ひ","hi"],["ふ","fu"],["へ","he"],["ほ","ho"],
    ["ま","ma"],["み","mi"],["む","mu"],["め","me"],["も","mo"],["や","ya"],["ゆ","yu"],["よ","yo"],["ら","ra"],["り","ri"],
    ["る","ru"],["れ","re"],["ろ","ro"],["わ","wa"],["を","wo"],["ん","n"],
    ["が","ga"],["ぎ","gi"],["ぐ","gu"],["げ","ge"],["ご","go"],["ざ","za"],["じ","ji"],["ず","zu"],["ぜ","ze"],["ぞ","zo"],
    ["だ","da"],["ぢ","ji"],["づ","zu"],["で","de"],["ど","do"],["ば","ba"],["び","bi"],["ぶ","bu"],["べ","be"],["ぼ","bo"],
    ["ぱ","pa"],["ぴ","pi"],["ぷ","pu"],["ぺ","pe"],["ぽ","po"],
    ["きゃ","kya"],["きゅ","kyu"],["きょ","kyo"],["しゃ","sha"],["しゅ","shu"],["しょ","sho"],["ちゃ","cha"],["ちゅ","chu"],["ちょ","cho"],
    ["にゃ","nya"],["にゅ","nyu"],["にょ","nyo"],["ひゃ","hya"],["ひゅ","hyu"],["ひょ","hyo"],["みゃ","mya"],["みゅ","myu"],["みょ","myo"],
    ["りゃ","rya"],["りゅ","ryu"],["りょ","ryo"],["ぎゃ","gya"],["ぎゅ","gyu"],["ぎょ","gyo"],["じゃ","ja"],["じゅ","ju"],["じょ","jo"],
    ["びゃ","bya"],["びゅ","byu"],["びょ","byo"],["ぴゃ","pya"],["ぴゅ","pyu"],["ぴょ","pyo"],
    ["N5", "会う", "あう · au", "treffen", "友達に会います。", "Ich treffe einen Freund."],
    ["N5", "開ける", "あける · akeru", "öffnen", "窓を開けます。", "Ich öffne das Fenster."],
    ["N5", "閉める", "しめる · shimeru", "schließen", "ドアを閉めます。", "Ich schließe die Tür."],
    ["N5", "起きる", "おきる · okiru", "aufstehen", "毎朝七時に起きます。", "Ich stehe jeden Morgen um sieben auf."],
    ["N5", "寝る", "ねる · neru", "schlafen gehen", "十一時に寝ます。", "Ich gehe um elf Uhr schlafen."],
    ["N5", "働く", "はたらく · hataraku", "arbeiten", "会社で働きます。", "Ich arbeite in einer Firma."],
    ["N5", "休む", "やすむ · yasumu", "sich ausruhen / frei nehmen", "日曜日は休みます。", "Sonntags ruhe ich mich aus."],
    ["N5", "待つ", "まつ · matsu", "warten", "駅で友達を待ちます。", "Ich warte am Bahnhof auf einen Freund."],
    ["N5", "持つ", "もつ · motsu", "halten / besitzen", "かばんを持っています。", "Ich habe eine Tasche dabei."],
    ["N5", "使う", "つかう · tsukau", "benutzen", "このペンを使います。", "Ich benutze diesen Stift."],
    ["N5", "作る", "つくる · tsukuru", "machen / herstellen", "夕ご飯を作ります。", "Ich mache Abendessen."],
    ["N5", "入る", "はいる · hairu", "hineingehen", "部屋に入ります。", "Ich gehe ins Zimmer."],
    ["N5", "出る", "でる · deru", "hinausgehen / verlassen", "家を出ます。", "Ich verlasse das Haus."],
    ["N5", "座る", "すわる · suwaru", "sitzen", "ここに座ってください。", "Bitte setzen Sie sich hier."],
    ["N5", "立つ", "たつ · tatsu", "stehen / aufstehen", "立ってください。", "Bitte stehen Sie auf."],
    ["N5", "分かる", "わかる · wakaru", "verstehen", "日本語が少し分かります。", "Ich verstehe ein wenig Japanisch."],
    ["N5", "教える", "おしえる · oshieru", "lehren / sagen", "先生が日本語を教えます。", "Der Lehrer unterrichtet Japanisch."],
    ["N5", "習う", "ならう · narau", "lernen / Unterricht nehmen", "日本語を習っています。", "Ich lerne Japanisch im Unterricht."],
    ["N5", "勉強する", "べんきょうする · benkyō suru", "lernen", "毎日日本語を勉強します。", "Ich lerne jeden Tag Japanisch."],
    ["N5", "始める", "はじめる · hajimeru", "beginnen", "勉強を始めます。", "Ich beginne zu lernen."],
    ["N5", "終わる", "おわる · owaru", "enden", "仕事は五時に終わります。", "Die Arbeit endet um fünf."],
    ["N5", "住む", "すむ · sumu", "wohnen", "東京に住んでいます。", "Ich wohne in Tokio."],
    ["N5", "歩く", "あるく · aruku", "zu Fuß gehen", "駅まで歩きます。", "Ich gehe zu Fuß zum Bahnhof."],
    ["N5", "走る", "はしる · hashiru", "laufen", "公園を走ります。", "Ich laufe im Park."],
    ["N5", "泳ぐ", "およぐ · oyogu", "schwimmen", "海で泳ぎます。", "Ich schwimme im Meer."],
    ["N5", "乗る", "のる · noru", "einsteigen / fahren", "電車に乗ります。", "Ich fahre mit dem Zug."],
    ["N5", "降りる", "おりる · oriru", "aussteigen", "次の駅で降ります。", "Ich steige an der nächsten Station aus."],
    ["N5", "曲がる", "まがる · magaru", "abbiegen", "右に曲がってください。", "Bitte biegen Sie rechts ab."],
    ["N5", "着く", "つく · tsuku", "ankommen", "九時に駅に着きます。", "Ich komme um neun am Bahnhof an."],
    ["N5", "帰る", "かえる · kaeru", "zurückkehren", "家に帰ります。", "Ich gehe nach Hause."],
    ["N5", "切る", "きる · kiru", "schneiden", "紙を切ります。", "Ich schneide Papier."],
    ["N5", "洗う", "あらう · arau", "waschen", "手を洗います。", "Ich wasche meine Hände."],
    ["N5", "掃除する", "そうじする · sōji suru", "putzen", "部屋を掃除します。", "Ich putze das Zimmer."],
    ["N5", "料理する", "りょうりする · ryōri suru", "kochen", "毎晩料理します。", "Ich koche jeden Abend."],
    ["N5", "電話する", "でんわする · denwa suru", "telefonieren", "母に電話します。", "Ich rufe meine Mutter an."],
    ["N5", "買い物する", "かいものする · kaimono suru", "einkaufen", "スーパーで買い物します。", "Ich kaufe im Supermarkt ein."],
    ["N5", "高い", "たかい · takai", "teuer / hoch", "このかばんは高いです。", "Diese Tasche ist teuer."],
    ["N5", "安い", "やすい · yasui", "billig", "この店は安いです。", "Dieses Geschäft ist günstig."],
    ["N5", "暑い", "あつい · atsui", "heiß", "今日は暑いです。", "Heute ist es heiß."],
    ["N5", "寒い", "さむい · samui", "kalt", "冬は寒いです。", "Im Winter ist es kalt."],
    ["N5", "暖かい", "あたたかい · atatakai", "warm", "今日は暖かいです。", "Heute ist es warm."],
    ["N5", "涼しい", "すずしい · suzushii", "kühl / angenehm", "夜は涼しいです。", "Abends ist es angenehm kühl."],
    ["N5", "難しい", "むずかしい · muzukashii", "schwierig", "漢字は難しいです。", "Kanji sind schwierig."],
    ["N5", "易しい", "やさしい · yasashii", "einfach", "この問題は易しいです。", "Diese Aufgabe ist einfach."],
    ["N5", "面白い", "おもしろい · omoshiroi", "interessant", "この本は面白いです。", "Dieses Buch ist interessant."],
    ["N5", "忙しい", "いそがしい · isogashii", "beschäftigt", "今日は忙しいです。", "Heute bin ich beschäftigt."],
    ["N5", "楽しい", "たのしい · tanoshii", "spaßig / angenehm", "旅行は楽しいです。", "Reisen macht Spaß."],
    ["N5", "近い", "ちかい · chikai", "nah", "駅は近いです。", "Der Bahnhof ist nah."],
    ["N5", "遠い", "とおい · tōi", "weit", "学校は遠いです。", "Die Schule ist weit weg."],
    ["N5", "早い", "はやい · hayai", "früh / schnell", "朝早く起きます。", "Ich stehe früh auf."],
    ["N5", "遅い", "おそい · osoi", "spät / langsam", "電車が遅いです。", "Der Zug ist langsam/spät."],
    ["N5", "長い", "ながい · nagai", "lang", "長い映画です。", "Es ist ein langer Film."],
    ["N5", "短い", "みじかい · mijikai", "kurz", "短い休みです。", "Es ist eine kurze Pause."],
    ["N5", "白い", "しろい · shiroi", "weiß", "白い車です。", "Es ist ein weißes Auto."],
    ["N5", "黒い", "くろい · kuroi", "schwarz", "黒いかばんです。", "Es ist eine schwarze Tasche."],
    ["N5", "赤い", "あかい · akai", "rot", "赤いりんごです。", "Es ist ein roter Apfel."],
    ["N5", "青い", "あおい · aoi", "blau", "青い空です。", "Der Himmel ist blau."],
    ["N5", "好き", "すき · suki", "mögen", "音楽が好きです。", "Ich mag Musik."],
    ["N5", "嫌い", "きらい · kirai", "nicht mögen", "魚が嫌いです。", "Ich mag Fisch nicht."],
    ["N5", "元気", "げんき · genki", "gesund / fit", "元気ですか。", "Wie geht es dir?"],
    ["N5", "静か", "しずか · shizuka", "ruhig", "この部屋は静かです。", "Dieses Zimmer ist ruhig."],
    ["N5", "にぎやか", "nigiyaka", "lebhaft", "町はにぎやかです。", "Die Stadt ist lebhaft."],
    ["N5", "きれい", "kirei", "schön / sauber", "部屋はきれいです。", "Das Zimmer ist sauber."],
    ["N5", "便利", "べんり · benri", "praktisch", "このアプリは便利です。", "Diese App ist praktisch."],
    ["N5", "不便", "ふべん · fuben", "unpraktisch", "ここは少し不便です。", "Hier ist es etwas unpraktisch."],
    ["N5", "春", "はる · haru", "Frühling", "春は暖かいです。", "Im Frühling ist es warm."],
    ["N5", "夏", "なつ · natsu", "Sommer", "夏は暑いです。", "Im Sommer ist es heiß."],
    ["N5", "秋", "あき · aki", "Herbst", "秋が好きです。", "Ich mag den Herbst."],
    ["N5", "冬", "ふゆ · fuyu", "Winter", "冬は寒いです。", "Im Winter ist es kalt."],
    ["N5", "天気", "てんき · tenki", "Wetter", "今日はいい天気です。", "Heute ist gutes Wetter."],
    ["N5", "雨", "あめ · ame", "Regen", "雨が降っています。", "Es regnet."],
    ["N5", "雪", "ゆき · yuki", "Schnee", "雪が降ります。", "Es schneit."],
    ["N5", "風", "かぜ · kaze", "Wind", "風が強いです。", "Der Wind ist stark."],
    ["N5", "空", "そら · sora", "Himmel", "空が青いです。", "Der Himmel ist blau."],
    ["N5", "海", "うみ · umi", "Meer", "海で泳ぎます。", "Ich schwimme im Meer."],
    ["N5", "町", "まち · machi", "Stadt / Ort", "この町は静かです。", "Diese Stadt ist ruhig."],
    ["N5", "国", "くに · kuni", "Land", "どの国から来ましたか。", "Aus welchem Land kommst du?"],
    ["N5", "家", "いえ · ie", "Haus", "家に帰ります。", "Ich gehe nach Hause."],
    ["N5", "部屋", "へや · heya", "Zimmer", "部屋は二階です。", "Das Zimmer ist im zweiten Stock."],
    ["N5", "机", "つくえ · tsukue", "Schreibtisch", "本は机の上です。", "Das Buch liegt auf dem Schreibtisch."],
    ["N5", "椅子", "いす · isu", "Stuhl", "椅子に座ります。", "Ich setze mich auf den Stuhl."],
    ["N5", "窓", "まど · mado", "Fenster", "窓を開けます。", "Ich öffne das Fenster."],
    ["N5", "ドア", "doa", "Tür", "ドアを閉めます。", "Ich schließe die Tür."],
    ["N5", "本", "ほん · hon", "Buch", "本を読みます。", "Ich lese ein Buch."],
    ["N5", "新聞", "しんぶん · shinbun", "Zeitung", "新聞を読みます。", "Ich lese Zeitung."],
    ["N5", "手紙", "てがみ · tegami", "Brief", "手紙を書きます。", "Ich schreibe einen Brief."],
    ["N5", "写真", "しゃしん · shashin", "Foto", "写真を撮ります。", "Ich mache ein Foto."],
    ["N5", "時計", "とけい · tokei", "Uhr", "時計を見ます。", "Ich schaue auf die Uhr."],
    ["N5", "電話", "でんわ · denwa", "Telefon", "電話を使います。", "Ich benutze das Telefon."],
    ["N5", "車", "くるま · kuruma", "Auto", "車で行きます。", "Ich fahre mit dem Auto."],
    ["N5", "電車", "でんしゃ · densha", "Zug", "電車に乗ります。", "Ich fahre mit dem Zug."],
    ["N5", "自転車", "じてんしゃ · jitensha", "Fahrrad", "自転車で学校へ行きます。", "Ich fahre mit dem Fahrrad zur Schule."],
    ["N5", "飛行機", "ひこうき · hikōki", "Flugzeug", "飛行機で日本へ行きます。", "Ich fliege nach Japan."],
    ["N5", "食べ物", "たべもの · tabemono", "Essen / Lebensmittel", "日本の食べ物が好きです。", "Ich mag japanisches Essen."],
    ["N5", "飲み物", "のみもの · nomimono", "Getränk", "飲み物は何ですか。", "Was möchtest du trinken?"],
    ["N5", "肉", "にく · niku", "Fleisch", "肉を食べます。", "Ich esse Fleisch."],
    ["N5", "魚", "さかな · sakana", "Fisch", "魚が好きです。", "Ich mag Fisch."],
    ["N5", "野菜", "やさい · yasai", "Gemüse", "野菜を食べます。", "Ich esse Gemüse."],
    ["N5", "果物", "くだもの · kudamono", "Obst", "果物を買います。", "Ich kaufe Obst."],
    ["N5", "パン", "pan", "Brot", "朝パンを食べます。", "Morgens esse ich Brot."],
    ["N5", "牛乳", "ぎゅうにゅう · gyūnyū", "Milch", "牛乳を飲みます。", "Ich trinke Milch."],
    ["N5", "卵", "たまご · tamago", "Ei", "卵を二つ買います。", "Ich kaufe zwei Eier."],
    ["N5", "お金", "おかね · okane", "Geld", "お金があります。", "Ich habe Geld."],
    ["N5", "円", "えん · en", "Yen", "千円です。", "Es kostet 1000 Yen."],
    ["N5", "時間", "じかん · jikan", "Zeit / Stunden", "時間がありますか。", "Hast du Zeit?"],
    ["N5", "分", "ふん / ぷん · fun / pun", "Minute", "十分待ってください。", "Bitte warten Sie zehn Minuten."],
    ["N5", "週", "しゅう · shū", "Woche", "一週間休みます。", "Ich habe eine Woche frei."],
    ["N5", "月曜日", "げつようび · getsuyōbi", "Montag", "月曜日に働きます。", "Ich arbeite am Montag."],
    ["N5", "火曜日", "かようび · kayōbi", "Dienstag", "火曜日に勉強します。", "Ich lerne am Dienstag."],
    ["N5", "水曜日", "すいようび · suiyōbi", "Mittwoch", "水曜日は休みです。", "Mittwoch habe ich frei."],
    ["N5", "木曜日", "もくようび · mokuyōbi", "Donnerstag", "木曜日に会いましょう。", "Treffen wir uns am Donnerstag."],
    ["N5", "金曜日", "きんようび · kin'yōbi", "Freitag", "金曜日は忙しいです。", "Freitag bin ich beschäftigt."],
    ["N5", "土曜日", "どようび · doyōbi", "Samstag", "土曜日に買い物します。", "Samstags gehe ich einkaufen."],
    ["N5", "日曜日", "にちようび · nichiyōbi", "Sonntag", "日曜日は休みます。", "Sonntags ruhe ich mich aus."],
    ["N4", "赤ちゃん", "あかちゃん · akachan", "Baby", "赤ちゃんが寝ています。", "Das Baby schläft."],
    ["N4", "味", "あじ · aji", "Geschmack", "このスープは味が薄いです。", "Diese Suppe schmeckt mild."],
    ["N4", "安心", "あんしん · anshin", "Beruhigung / Sicherheit", "無事だと聞いて安心しました。", "Ich war beruhigt, als ich hörte, dass alles in Ordnung ist."],
    ["N4", "安全", "あんぜん · anzen", "Sicherheit", "ここは安全です。", "Hier ist es sicher."],
    ["N4", "案内", "あんない · annai", "Führung / Information", "駅まで案内します。", "Ich zeige Ihnen den Weg zum Bahnhof."],
    ["N4", "以下", "いか · ika", "höchstens / darunter", "十歳以下は無料です。", "Kinder bis zehn Jahre sind kostenlos."],
    ["N4", "以外", "いがい · igai", "außer", "日曜日以外は開いています。", "Außer sonntags ist geöffnet."],
    ["N4", "医学", "いがく · igaku", "Medizin", "大学で医学を学んでいます。", "Ich studiere Medizin an der Universität."],
    ["N4", "意見", "いけん · iken", "Meinung", "あなたの意見を聞きたいです。", "Ich möchte Ihre Meinung hören."],
    ["N4", "石", "いし · ishi", "Stein", "道に大きな石があります。", "Auf dem Weg liegt ein großer Stein."],
    ["N4", "一度", "いちど · ichido", "einmal", "一度日本へ行きたいです。", "Ich möchte einmal nach Japan reisen."],
    ["N4", "一生懸命", "いっしょうけんめい · isshōkenmei", "mit vollem Einsatz", "一生懸命勉強しています。", "Ich lerne sehr fleißig."],
    ["N4", "受付", "うけつけ · uketsuke", "Empfang / Rezeption", "受付で名前を書いてください。", "Bitte schreiben Sie Ihren Namen an der Rezeption auf."],
    ["N4", "腕", "うで · ude", "Arm", "腕が痛いです。", "Mein Arm tut weh."],
    ["N4", "運転", "うんてん · unten", "Fahren", "父は毎日車を運転します。", "Mein Vater fährt jeden Tag Auto."],
    ["N4", "運転手", "うんてんしゅ · untenshu", "Fahrer/in", "バスの運転手です。", "Er/Sie ist Busfahrer/in."],
    ["N4", "駅員", "えきいん · ekiin", "Bahnhofsangestellte/r", "駅員に聞きました。", "Ich habe den Bahnhofsangestellten gefragt."],
    ["N4", "枝", "えだ · eda", "Ast", "木の枝に鳥がいます。", "Auf einem Ast sitzt ein Vogel."],
    ["N4", "遠慮", "えんりょ · enryo", "Zurückhaltung", "遠慮しないでください。", "Bitte seien Sie nicht zurückhaltend."],
    ["N4", "お祝い", "おいわい · oiwai", "Feier / Glückwunsch", "誕生日のお祝いをします。", "Wir feiern Geburtstag."],
    ["N4", "屋上", "おくじょう · okujō", "Dachterrasse", "屋上から町が見えます。", "Von der Dachterrasse sieht man die Stadt."],
    ["N4", "贈り物", "おくりもの · okurimono", "Geschenk", "友達に贈り物をしました。", "Ich habe einem Freund ein Geschenk gemacht."],
    ["N4", "お宅", "おたく · otaku", "Ihr Zuhause", "明日お宅へ伺います。", "Ich komme morgen zu Ihnen nach Hause."],
    ["N4", "お土産", "おみやげ · omiyage", "Souvenir", "家族にお土産を買いました。", "Ich habe meiner Familie ein Souvenir gekauft."],
    ["N4", "会議", "かいぎ · kaigi", "Besprechung", "午後に会議があります。", "Am Nachmittag gibt es eine Besprechung."],
    ["N4", "会場", "かいじょう · kaijō", "Veranstaltungsort", "会場は二階です。", "Der Veranstaltungsort ist im zweiten Stock."],
    ["N4", "会話", "かいわ · kaiwa", "Gespräch", "日本語で会話を練習します。", "Ich übe Gespräche auf Japanisch."],
    ["N4", "帰り", "かえり · kaeri", "Rückweg", "帰りにスーパーへ寄ります。", "Auf dem Rückweg gehe ich noch zum Supermarkt."],
    ["N4", "科学", "かがく · kagaku", "Wissenschaft", "科学に興味があります。", "Ich interessiere mich für Wissenschaft."],
    ["N4", "鏡", "かがみ · kagami", "Spiegel", "鏡を見ます。", "Ich schaue in den Spiegel."],
    ["N4", "飾る", "かざる · kazaru", "dekorieren", "部屋に花を飾ります。", "Ich dekoriere das Zimmer mit Blumen."],
    ["N4", "ガス", "gasu", "Gas", "ガスを止めてください。", "Bitte stellen Sie das Gas ab."],
    ["N4", "形", "かたち · katachi", "Form", "この箱は変わった形です。", "Diese Schachtel hat eine ungewöhnliche Form."],
    ["N4", "片付ける", "かたづける · katazukeru", "aufräumen", "部屋を片付けます。", "Ich räume das Zimmer auf."],
    ["N4", "勝つ", "かつ · katsu", "gewinnen", "試合に勝ちました。", "Wir haben das Spiel gewonnen."],
    ["N4", "悲しい", "かなしい · kanashii", "traurig", "その話を聞いて悲しくなりました。", "Die Geschichte hat mich traurig gemacht."],
    ["N4", "必ず", "かならず · kanarazu", "unbedingt / sicher", "明日は必ず来てください。", "Bitte kommen Sie morgen unbedingt."],
    ["N4", "彼", "かれ · kare", "er / Freund", "彼は会社員です。", "Er ist Angestellter."],
    ["N4", "彼女", "かのじょ · kanojo", "sie / Freundin", "彼女は学生です。", "Sie ist Studentin."],
    ["N4", "乾く", "かわく · kawaku", "trocknen", "服がまだ乾いていません。", "Die Kleidung ist noch nicht trocken."],
    ["N4", "変わる", "かわる · kawaru", "sich ändern", "予定が変わりました。", "Der Plan hat sich geändert."],
    ["N4", "考える", "かんがえる · kangaeru", "denken / überlegen", "少し考えてください。", "Bitte denken Sie kurz darüber nach."],
    ["N4", "関係", "かんけい · kankei", "Beziehung / Zusammenhang", "仕事と生活は関係があります。", "Arbeit und Leben hängen zusammen."],
    ["N4", "看護師", "かんごし · kangoshi", "Pflegekraft", "姉は看護師です。", "Meine ältere Schwester ist Pflegekraft."],
    ["N4", "簡単", "かんたん · kantan", "einfach", "この問題は簡単です。", "Diese Aufgabe ist einfach."],
    ["N4", "気", "き · ki", "Gefühl / Aufmerksamkeit", "気をつけてください。", "Bitte passen Sie auf."],
    ["N4", "機会", "きかい · kikai", "Gelegenheit", "日本語を話す機会がありません。", "Ich habe keine Gelegenheit, Japanisch zu sprechen."],
    ["N4", "危険", "きけん · kiken", "Gefahr / gefährlich", "ここは危険です。", "Hier ist es gefährlich."],
    ["N4", "聞こえる", "きこえる · kikoeru", "hörbar sein", "音が聞こえます。", "Man kann ein Geräusch hören."],
    ["N4", "決まる", "きまる · kimaru", "entschieden werden", "日程が決まりました。", "Der Termin steht fest."],
    ["N4", "決める", "きめる · kimeru", "entscheiden", "旅行の日を決めます。", "Ich entscheide den Reisetag."],
    ["N4", "気持ち", "きもち · kimochi", "Gefühl", "今の気持ちを話してください。", "Bitte sprechen Sie über Ihr momentanes Gefühl."],
    ["N4", "急", "きゅう · kyū", "plötzlich / dringend", "急な予定が入りました。", "Es ist kurzfristig ein Termin dazugekommen."],
    ["N4", "急行", "きゅうこう · kyūkō", "Expresszug", "急行に乗ります。", "Ich nehme den Expresszug."],
    ["N4", "教育", "きょういく · kyōiku", "Bildung / Erziehung", "教育は大切です。", "Bildung ist wichtig."],
    ["N4", "興味", "きょうみ · kyōmi", "Interesse", "日本文化に興味があります。", "Ich interessiere mich für japanische Kultur."],
    ["N4", "近所", "きんじょ · kinjo", "Nachbarschaft", "近所に公園があります。", "In der Nachbarschaft gibt es einen Park."],
    ["N4", "具合", "ぐあい · guai", "Zustand / Befinden", "体の具合はどうですか。", "Wie geht es Ihnen körperlich?"],
    ["N4", "空気", "くうき · kūki", "Luft", "部屋の空気を入れ替えます。", "Ich lüfte das Zimmer."],
    ["N4", "空港", "くうこう · kūkō", "Flughafen", "空港までバスで行きます。", "Ich fahre mit dem Bus zum Flughafen."],
    ["N4", "比べる", "くらべる · kuraberu", "vergleichen", "二つの商品を比べます。", "Ich vergleiche zwei Produkte."],
    ["N4", "暮らす", "くらす · kurasu", "leben", "家族と東京で暮らしています。", "Ich lebe mit meiner Familie in Tokio."],
    ["N4", "計画", "けいかく · keikaku", "Plan", "旅行の計画を立てます。", "Ich plane eine Reise."],
    ["N4", "経験", "けいけん · keiken", "Erfahrung", "日本で働いた経験があります。", "Ich habe Erfahrung mit Arbeit in Japan."],
    ["N4", "警察", "けいさつ · keisatsu", "Polizei", "警察に電話しました。", "Ich habe die Polizei angerufen."],
    ["N4", "景色", "けしき · keshiki", "Landschaft / Aussicht", "山の景色がきれいです。", "Die Aussicht auf die Berge ist schön."],
    ["N4", "原因", "げんいん · gen'in", "Ursache", "事故の原因を調べます。", "Wir untersuchen die Unfallursache."],
    ["N4", "研究", "けんきゅう · kenkyū", "Forschung", "大学で研究しています。", "Ich forsche an der Universität."],
    ["N4", "健康", "けんこう · kenkō", "Gesundheit", "健康のために歩きます。", "Ich gehe der Gesundheit zuliebe spazieren."],
    ["N4", "見物", "けんぶつ · kenbutsu", "Besichtigung", "京都を見物しました。", "Ich habe Kyoto besichtigt."],
    ["N4", "工場", "こうじょう · kōjō", "Fabrik", "父は工場で働いています。", "Mein Vater arbeitet in einer Fabrik."],
    ["N4", "交通", "こうつう · kōtsū", "Verkehr", "この町は交通が便利です。", "Der Verkehr in dieser Stadt ist praktisch."],
    ["N4", "答え", "こたえ · kotae", "Antwort", "答えを書いてください。", "Bitte schreiben Sie die Antwort."],
    ["N4", "故障", "こしょう · koshō", "Defekt", "エアコンが故障しました。", "Die Klimaanlage ist kaputt."],
    ["N4", "ご存じ", "ごぞんじ · gozonji", "kennen / wissen (höflich)", "この店をご存じですか。", "Kennen Sie dieses Geschäft?"],
    ["N4", "込む", "こむ · komu", "überfüllt sein", "電車が込んでいます。", "Der Zug ist voll."],
    ["N4", "怖い", "こわい · kowai", "ängstlich / unheimlich", "夜道は少し怖いです。", "Der Weg bei Nacht ist etwas unheimlich."],
    ["N4", "壊す", "こわす · kowasu", "kaputt machen", "時計を壊してしまいました。", "Ich habe die Uhr kaputt gemacht."],
    ["N4", "壊れる", "こわれる · kowareru", "kaputtgehen", "パソコンが壊れました。", "Der Computer ist kaputtgegangen."],
    ["N4", "今度", "こんど · kondo", "nächstes Mal / diesmal", "今度一緒に行きましょう。", "Lass uns nächstes Mal zusammen gehen."],
    ["N4", "最近", "さいきん · saikin", "in letzter Zeit", "最近忙しいです。", "In letzter Zeit bin ich beschäftigt."],
    ["N4", "最後", "さいご · saigo", "letzte/r/s", "最後のページを読みます。", "Ich lese die letzte Seite."],
    ["N4", "最初", "さいしょ · saisho", "erste/r/s", "最初に名前を書きます。", "Zuerst schreibe ich den Namen."],
    ["N4", "坂", "さか · saka", "Hang / Steigung", "この坂は急です。", "Dieser Hang ist steil."],
    ["N4", "探す", "さがす · sagasu", "suchen", "鍵を探しています。", "Ich suche den Schlüssel."],
    ["N4", "下がる", "さがる · sagaru", "sinken", "気温が下がりました。", "Die Temperatur ist gesunken."],
    ["N4", "下げる", "さげる · sageru", "senken", "音を下げてください。", "Bitte machen Sie leiser."],
    ["N4", "差し上げる", "さしあげる · sashiageru", "geben (höflich)", "先生にお土産を差し上げました。", "Ich habe dem Lehrer ein Souvenir gegeben."],
    ["N4", "十分", "じゅうぶん · jūbun", "genug / ausreichend", "時間は十分あります。", "Es ist genug Zeit da."],
    ["N4", "自由", "じゆう · jiyū", "Freiheit / frei", "自由に使ってください。", "Bitte benutzen Sie es frei."],
    ["N4", "習慣", "しゅうかん · shūkan", "Gewohnheit", "毎朝歩く習慣があります。", "Ich habe die Gewohnheit, jeden Morgen zu gehen."],
    ["N4", "住所", "じゅうしょ · jūsho", "Adresse", "住所を書いてください。", "Bitte schreiben Sie Ihre Adresse."],
    ["N4", "出発", "しゅっぱつ · shuppatsu", "Abfahrt / Abreise", "七時に出発します。", "Wir fahren um sieben ab."],
    ["N4", "準備", "じゅんび · junbi", "Vorbereitung", "旅行の準備をします。", "Ich bereite die Reise vor."],
    ["N4", "紹介", "しょうかい · shōkai", "Vorstellung / Einführung", "友達を紹介します。", "Ich stelle einen Freund vor."],
    ["N4", "小説", "しょうせつ · shōsetsu", "Roman", "日本の小説を読みます。", "Ich lese einen japanischen Roman."],
    ["N4", "将来", "しょうらい · shōrai", "Zukunft", "将来日本で働きたいです。", "Ich möchte später in Japan arbeiten."],
    ["N4", "知らせる", "しらせる · shiraseru", "informieren", "時間が決まったら知らせます。", "Ich sage Bescheid, sobald die Zeit feststeht."],
    ["N4", "調べる", "しらべる · shiraberu", "nachschlagen / untersuchen", "辞書で意味を調べます。", "Ich schlage die Bedeutung im Wörterbuch nach."],
    ["N4", "人口", "じんこう · jinkō", "Bevölkerung", "東京は人口が多いです。", "Tokio hat eine große Bevölkerung."],
    ["N4", "親切", "しんせつ · shinsetsu", "freundlich / hilfsbereit", "店員はとても親切でした。", "Der Verkäufer war sehr freundlich."],
    ["N4", "心配", "しんぱい · shinpai", "Sorge", "そんなに心配しないでください。", "Bitte machen Sie sich nicht so viele Sorgen."],
    ["N4", "進む", "すすむ · susumu", "vorangehen", "工事が進んでいます。", "Die Bauarbeiten kommen voran."],
    ["N4", "進める", "すすめる · susumeru", "vorantreiben", "計画を進めます。", "Ich treibe den Plan voran."],
    ["N4", "捨てる", "すてる · suteru", "wegwerfen", "ごみを捨てます。", "Ich werfe den Müll weg."],
    ["N4", "生活", "せいかつ · seikatsu", "Leben / Alltag", "日本の生活に慣れました。", "Ich habe mich an das Leben in Japan gewöhnt."],
    ["N4", "説明", "せつめい · setsumei", "Erklärung", "使い方を説明します。", "Ich erkläre die Benutzung."],
    ["N4", "選ぶ", "えらぶ · erabu", "auswählen", "好きなものを選んでください。", "Bitte wählen Sie etwas aus, das Sie mögen."],
    ["N4", "相談", "そうだん · sōdan", "Beratung / Besprechung", "先生に相談します。", "Ich bespreche es mit dem Lehrer."],
    ["N4", "育てる", "そだてる · sodateru", "aufziehen / anbauen", "庭で野菜を育てています。", "Ich baue im Garten Gemüse an."],
    ["N4", "卒業", "そつぎょう · sotsugyō", "Abschluss", "来年大学を卒業します。", "Nächstes Jahr mache ich meinen Uniabschluss."],
    ["N4", "大体", "だいたい · daitai", "ungefähr / im Großen und Ganzen", "大体分かりました。", "Ich habe es ungefähr verstanden."],
    ["N4", "確か", "たしか · tashika", "sicher / wenn ich mich recht erinnere", "確か三時でした。", "Wenn ich mich recht erinnere, war es drei Uhr."],
    ["N4", "訪ねる", "たずねる · tazuneru", "besuchen", "友達を訪ねます。", "Ich besuche einen Freund."],
    ["N4", "尋ねる", "たずねる · tazuneru", "fragen", "駅員に道を尋ねました。", "Ich fragte den Bahnhofsangestellten nach dem Weg."],
    ["N4", "建てる", "たてる · tateru", "bauen", "新しい家を建てています。", "Sie bauen ein neues Haus."],
    ["N4", "足りる", "たりる · tariru", "ausreichen", "お金が足りません。", "Das Geld reicht nicht."],
    ["N4", "暖房", "だんぼう · danbō", "Heizung", "暖房をつけます。", "Ich schalte die Heizung ein."],
    ["N4", "注意", "ちゅうい · chūi", "Vorsicht / Aufmerksamkeit", "車に注意してください。", "Bitte achten Sie auf Autos."],
    ["N4", "駐車場", "ちゅうしゃじょう · chūshajō", "Parkplatz", "駐車場はどこですか。", "Wo ist der Parkplatz?"],
    ["N4", "都合", "つごう · tsugō", "Umstände / Verfügbarkeit", "明日は都合が悪いです。", "Morgen passt es mir nicht."],
    ["N4", "続く", "つづく · tsuzuku", "andauern", "雨が三日続きました。", "Der Regen dauerte drei Tage an."],
    ["N4", "続ける", "つづける · tsuzukeru", "fortsetzen", "勉強を続けます。", "Ich lerne weiter."],
    ["N4", "伝える", "つたえる · tsutaeru", "übermitteln", "先生に伝えてください。", "Bitte richten Sie es dem Lehrer aus."],
    ["N4", "包む", "つつむ · tsutsumu", "einpacken", "プレゼントを包みます。", "Ich packe das Geschenk ein."],
    ["N4", "丁寧", "ていねい · teinei", "höflich / sorgfältig", "丁寧に書いてください。", "Bitte schreiben Sie sorgfältig."],
    ["N4", "適当", "てきとう · tekitō", "geeignet / passend", "適当な時間を選んでください。", "Bitte wählen Sie eine passende Zeit."],
    ["N4", "手伝う", "てつだう · tetsudau", "helfen", "母の料理を手伝います。", "Ich helfe meiner Mutter beim Kochen."],
    ["N4", "途中", "とちゅう · tochū", "unterwegs / mittendrin", "途中で雨が降りました。", "Unterwegs begann es zu regnen."],
    ["N4", "届ける", "とどける · todokeru", "zustellen / bringen", "荷物を家まで届けます。", "Wir liefern das Paket bis nach Hause."],
    ["N4", "泊まる", "とまる · tomaru", "übernachten", "ホテルに泊まります。", "Ich übernachte im Hotel."],
    ["N4", "直す", "なおす · naosu", "reparieren / korrigieren", "自転車を直します。", "Ich repariere das Fahrrad."],
    ["N4", "治る", "なおる · naoru", "heilen", "風邪が治りました。", "Meine Erkältung ist vorbei."],
    ["N4", "治す", "なおす · naosu", "heilen / behandeln", "病気を治します。", "Ich behandle die Krankheit."],
    ["N4", "慣れる", "なれる · nareru", "sich gewöhnen", "日本の生活に慣れました。", "Ich habe mich an das Leben in Japan gewöhnt."],
    ["N4", "似る", "にる · niru", "ähnlich sein", "母によく似ています。", "Er/Sie sieht der Mutter sehr ähnlich."],
    ["N4", "入院", "にゅういん · nyūin", "Krankenhausaufnahme", "祖父が入院しました。", "Mein Großvater wurde ins Krankenhaus aufgenommen."],
    ["N4", "眠い", "ねむい · nemui", "schläfrig", "今日はとても眠いです。", "Heute bin ich sehr müde."],
    ["N4", "残る", "のこる · nokoru", "übrig bleiben", "料理が少し残りました。", "Etwas Essen ist übrig geblieben."],
    ["N4", "乗り換える", "のりかえる · norikaeru", "umsteigen", "東京駅で乗り換えます。", "Ich steige am Bahnhof Tokio um."],
    ["N4", "場合", "ばあい · baai", "Fall / Situation", "雨の場合は中止です。", "Bei Regen fällt es aus."],
    ["N4", "倍", "ばい · bai", "doppelt / -fach", "値段が二倍になりました。", "Der Preis hat sich verdoppelt."],
    ["N4", "運ぶ", "はこぶ · hakobu", "tragen / transportieren", "荷物を運びます。", "Ich trage das Gepäck."],
    ["N4", "始まる", "はじまる · hajimaru", "beginnen", "映画は七時に始まります。", "Der Film beginnt um sieben."],
    ["N4", "発音", "はつおん · hatsuon", "Aussprache", "発音を練習します。", "Ich übe die Aussprache."],
    ["N4", "払う", "はらう · harau", "bezahlen", "カードで払います。", "Ich bezahle mit Karte."],
    ["N4", "冷える", "ひえる · hieru", "kalt werden", "夜はかなり冷えます。", "Nachts wird es ziemlich kalt."],
    ["N4", "光", "ひかり · hikari", "Licht", "窓から光が入ります。", "Durch das Fenster fällt Licht herein."],
    ["N4", "引っ越す", "ひっこす · hikkosu", "umziehen", "来月大阪へ引っ越します。", "Nächsten Monat ziehe ich nach Osaka."],
    ["N4", "必要", "ひつよう · hitsuyō", "notwendig", "パスポートが必要です。", "Ein Reisepass ist notwendig."],
    ["N4", "増える", "ふえる · fueru", "zunehmen", "観光客が増えました。", "Die Zahl der Touristen ist gestiegen."],
    ["N4", "増やす", "ふやす · fuyasu", "erhöhen", "勉強時間を増やします。", "Ich erhöhe meine Lernzeit."],
    ["N4", "復習", "ふくしゅう · fukushū", "Wiederholung", "毎日復習します。", "Ich wiederhole jeden Tag."],
    ["N4", "普通", "ふつう · futsū", "normal / gewöhnlich", "普通の電車に乗ります。", "Ich nehme den normalen Zug."],
    ["N4", "文化", "ぶんか · bunka", "Kultur", "日本文化を勉強しています。", "Ich lerne über japanische Kultur."],
    ["N4", "変", "へん · hen", "seltsam", "変な音がします。", "Es gibt ein seltsames Geräusch."],
    ["N4", "貿易", "ぼうえき · bōeki", "Handel", "この国は貿易が盛んです。", "In diesem Land ist der Handel stark."],
    ["N4", "法律", "ほうりつ · hōritsu", "Gesetz", "法律を守らなければなりません。", "Man muss das Gesetz einhalten."],
    ["N4", "間に合う", "まにあう · maniau", "rechtzeitig schaffen", "電車に間に合いました。", "Ich habe den Zug rechtzeitig erreicht."],
    ["N4", "間違える", "まちがえる · machigaeru", "sich irren", "答えを間違えました。", "Ich habe die Antwort falsch gemacht."],
    ["N4", "間違い", "まちがい · machigai", "Fehler", "間違いを直してください。", "Bitte korrigieren Sie den Fehler."],
    ["N4", "周り", "まわり · mawari", "Umgebung", "家の周りは静かです。", "Die Umgebung des Hauses ist ruhig."],
    ["N4", "見える", "みえる · mieru", "sichtbar sein", "ここから山が見えます。", "Von hier aus sieht man die Berge."],
    ["N4", "見つける", "みつける · mitsukeru", "finden", "いい店を見つけました。", "Ich habe ein gutes Geschäft gefunden."],
    ["N4", "迎える", "むかえる · mukaeru", "abholen / empfangen", "駅まで友達を迎えに行きます。", "Ich hole einen Freund am Bahnhof ab."],
    ["N4", "珍しい", "めずらしい · mezurashii", "selten / ungewöhnlich", "珍しい花を見ました。", "Ich habe eine seltene Blume gesehen."],
    ["N4", "申し込む", "もうしこむ · mōshikomu", "sich anmelden / beantragen", "コースに申し込みました。", "Ich habe mich für den Kurs angemeldet."],
    ["N4", "戻る", "もどる · modoru", "zurückkehren", "すぐ戻ります。", "Ich komme gleich zurück."],
    ["N4", "戻す", "もどす · modosu", "zurückstellen", "本を棚に戻します。", "Ich stelle das Buch ins Regal zurück."],
    ["N4", "役に立つ", "やくにたつ · yaku ni tatsu", "nützlich sein", "この辞書は役に立ちます。", "Dieses Wörterbuch ist nützlich."],
    ["N4", "予定", "よてい · yotei", "Plan / Termin", "明日の予定は何ですか。", "Was ist morgen geplant?"],
    ["N4", "予約", "よやく · yoyaku", "Reservierung", "ホテルを予約しました。", "Ich habe ein Hotel reserviert."],
    ["N4", "理由", "りゆう · riyū", "Grund", "理由を説明してください。", "Bitte erklären Sie den Grund."],
    ["N4", "利用", "りよう · riyō", "Nutzung", "このサービスを利用します。", "Ich nutze diesen Service."],
    ["N4", "留学", "りゅうがく · ryūgaku", "Auslandsstudium", "日本へ留学したいです。", "Ich möchte in Japan studieren."],
    ["N4", "両方", "りょうほう · ryōhō", "beide", "両方好きです。", "Ich mag beide."],
    ["N4", "連絡", "れんらく · renraku", "Kontakt / Nachricht", "後で連絡します。", "Ich melde mich später."],
    ["N4", "沸かす", "わかす · wakasu", "zum Kochen bringen", "お湯を沸かします。", "Ich koche Wasser."],
    ["N4", "笑う", "わらう · warau", "lachen", "みんなで笑いました。", "Wir haben alle gelacht."],
    ["N4", "～ながら", "nagara", "während", "音楽を聞きながら勉強します。", "Ich lerne, während ich Musik höre."],
    ["N4", "～と思う", "to omou", "denken, dass …", "明日は雨だと思います。", "Ich denke, dass es morgen regnet."],
    ["N4", "～と言う", "to iu", "sagen, dass …", "先生は明日休みだと言いました。", "Der Lehrer sagte, dass morgen frei ist."],
    ["N4", "～たことがある", "ta koto ga aru", "schon einmal getan haben", "日本へ行ったことがあります。", "Ich war schon einmal in Japan."],
    ["N4", "～たり～たりする", "tari tari suru", "unter anderem … tun", "休みの日は本を読んだり映画を見たりします。", "An freien Tagen lese ich unter anderem Bücher und schaue Filme."],
    ["N4", "～なければならない", "nakereba naranai", "müssen", "薬を飲まなければなりません。", "Ich muss Medizin nehmen."],
    ["N4", "～なくてもいい", "nakute mo ii", "nicht müssen", "明日は来なくてもいいです。", "Du musst morgen nicht kommen."],
    ["N4", "～かもしれない", "kamo shirenai", "vielleicht", "午後は雨が降るかもしれません。", "Vielleicht regnet es am Nachmittag."],
    ["N4", "～でしょう", "deshō", "wahrscheinlich / nicht wahr?", "明日は寒いでしょう。", "Morgen wird es wahrscheinlich kalt."],
    ["N4", "～そうだ（様態）", "sō da", "sieht so aus, als …", "雨が降りそうです。", "Es sieht nach Regen aus."],
    ["N4", "～そうだ（伝聞）", "sō da", "ich habe gehört, dass …", "田中さんは来ないそうです。", "Ich habe gehört, dass Herr/Frau Tanaka nicht kommt."],
    ["N4", "～ようと思う", "yō to omou", "vorhaben", "来年日本へ行こうと思っています。", "Ich habe vor, nächstes Jahr nach Japan zu fahren."],
    ["N4", "～予定だ", "yotei da", "geplant sein", "来月引っ越す予定です。", "Ich plane, nächsten Monat umzuziehen."],
    ["N4", "～つもりだ", "tsumori da", "beabsichtigen", "毎日勉強するつもりです。", "Ich habe vor, jeden Tag zu lernen."],
    ["N4", "～ほうがいい", "hō ga ii", "es ist besser, …", "早く寝たほうがいいです。", "Du solltest besser früh schlafen gehen."],
    ["N4", "～すぎる", "sugiru", "zu sehr / zu viel", "食べすぎました。", "Ich habe zu viel gegessen."],
    ["N4", "～やすい", "yasui", "leicht zu …", "この本は読みやすいです。", "Dieses Buch ist leicht zu lesen."],
    ["N4", "～にくい", "nikui", "schwer zu …", "この漢字は覚えにくいです。", "Dieses Kanji ist schwer zu merken."],
    ["N4", "～始める", "hajimeru", "anfangen zu …", "雨が降り始めました。", "Es hat angefangen zu regnen."],
    ["N4", "～終わる", "owaru", "fertig …", "本を読み終わりました。", "Ich habe das Buch fertig gelesen."],
    ["N4", "～続ける", "tsuzukeru", "weiter …", "日本語を勉強し続けます。", "Ich lerne weiter Japanisch."],
    ["N4", "～てみる", "te miru", "versuchen, … zu tun", "この料理を食べてみます。", "Ich probiere dieses Gericht."],
    ["N4", "～ておく", "te oku", "im Voraus tun", "ホテルを予約しておきます。", "Ich reserviere das Hotel im Voraus."],
    ["N4", "～てしまう", "te shimau", "vollständig / bedauerlicherweise tun", "財布を忘れてしまいました。", "Ich habe leider mein Portemonnaie vergessen."],
    ["N4", "～てある", "te aru", "absichtlich in einem Zustand sein", "窓が開けてあります。", "Das Fenster ist absichtlich geöffnet."],
    ["N4", "～ているところだ", "te iru tokoro da", "gerade dabei sein", "今ご飯を食べているところです。", "Ich esse gerade."],
    ["N4", "～るところだ", "ru tokoro da", "gerade im Begriff sein", "今から出かけるところです。", "Ich bin gerade im Begriff loszugehen."],
    ["N4", "～たところだ", "ta tokoro da", "gerade getan haben", "今帰ったところです。", "Ich bin gerade zurückgekommen."],
    ["N4", "～ようになる", "yō ni naru", "dazu kommen, dass / fähig werden", "日本語が話せるようになりました。", "Ich kann inzwischen Japanisch sprechen."],
    ["N4", "～ようにする", "yō ni suru", "darauf achten, dass", "毎日歩くようにしています。", "Ich achte darauf, täglich zu gehen."],
    ["N4", "～ので", "node", "weil", "雨なので出かけません。", "Weil es regnet, gehe ich nicht aus."],
    ["N4", "～のに", "noni", "obwohl", "勉強したのに忘れました。", "Obwohl ich gelernt habe, habe ich es vergessen."],
    ["N4", "～し", "shi", "und außerdem / weil", "この店は安いし、おいしいです。", "Dieses Restaurant ist günstig und außerdem lecker."],
    ["N4", "～なら", "nara", "wenn es um … geht / falls", "京都なら春がおすすめです。", "Wenn es um Kyoto geht, empfehle ich den Frühling."],
    ["N4", "～たら", "tara", "wenn / nachdem", "家に帰ったら電話します。", "Wenn ich zu Hause bin, rufe ich an."],
    ["N4", "～ば", "ba", "wenn", "時間があれば行きます。", "Wenn ich Zeit habe, gehe ich."],
    ["N4", "～と", "to", "wenn immer / sobald", "春になると暖かくなります。", "Wenn Frühling wird, wird es warm."],
    ["N4", "～ても", "te mo", "auch wenn", "雨が降っても行きます。", "Auch wenn es regnet, gehe ich."],
    ["N4", "～しか～ない", "shika nai", "nur", "千円しかありません。", "Ich habe nur 1000 Yen."],
    ["N4", "～でも", "demo", "zum Beispiel / selbst", "お茶でも飲みませんか。", "Wollen wir vielleicht Tee trinken?"],
    ["N4", "～について", "ni tsuite", "über / bezüglich", "日本文化について勉強します。", "Ich lerne über japanische Kultur."],
    ["N4", "～によると", "ni yoru to", "laut", "天気予報によると、明日は雨です。", "Laut Wetterbericht regnet es morgen."],
    ["N4", "～までに", "made ni", "bis spätestens", "五時までに帰ってください。", "Bitte kommen Sie bis fünf Uhr zurück."],
    ["N4", "～間に", "aida ni", "während", "子どもが寝ている間に勉強します。", "Ich lerne, während das Kind schläft."],
    ["N4", "～前に", "mae ni", "bevor", "寝る前に歯を磨きます。", "Vor dem Schlafengehen putze ich die Zähne."],
    ["N4", "～後で", "ato de", "nachdem / später", "仕事の後で買い物します。", "Nach der Arbeit gehe ich einkaufen."],
    ["N4", "～ために", "tame ni", "um … zu / für", "日本で働くために勉強しています。", "Ich lerne, um in Japan zu arbeiten."],
    ["N4", "～方", "kata", "Art und Weise", "使い方を教えてください。", "Bitte zeigen Sie mir, wie man es benutzt."],
    ["N4", "～かどうか", "ka dō ka", "ob oder nicht", "行くかどうかまだ決めていません。", "Ich habe noch nicht entschieden, ob ich gehe."],
    ["N4", "～ようだ", "yō da", "es scheint / wie", "彼は疲れているようです。", "Er scheint müde zu sein."],
    ["N4", "会", "かい・あ", "treffen / Versammlung", "会社・会う"],
    ["N4", "社", "しゃ", "Firma / Schrein", "会社"],
    ["N4", "同", "どう・おな", "gleich", "同じ"],
    ["N4", "事", "じ・こと", "Sache / Ereignis", "仕事"],
    ["N4", "自", "じ・みずか", "selbst", "自分"],
    ["N4", "動", "どう・うご", "bewegen", "動物"],
    ["N4", "使", "し・つか", "benutzen", "使う"],
    ["N4", "作", "さく・つく", "machen", "作文"],
    ["N4", "思", "し・おも", "denken", "思う"],
    ["N4", "持", "じ・も", "halten", "持つ"],
    ["N4", "待", "たい・ま", "warten", "待つ"],
    ["N4", "終", "しゅう・お", "Ende", "終わる"],
    ["N4", "始", "し・はじ", "beginnen", "始める"],
    ["N4", "着", "ちゃく・き", "ankommen / tragen", "到着・着る"],
    ["N4", "服", "ふく", "Kleidung", "洋服"],
    ["N4", "送", "そう・おく", "schicken", "送る"],
    ["N4", "度", "ど・たび", "Grad / Mal", "一度"],
    ["N4", "借", "しゃく・か", "leihen", "借りる"],
    ["N4", "貸", "たい・か", "verleihen", "貸す"],
    ["N4", "返", "へん・かえ", "zurückgeben", "返す"],
    ["N4", "教", "きょう・おし", "lehren", "教える"],
    ["N4", "習", "しゅう・なら", "lernen", "習う"],
    ["N4", "勉", "べん", "Anstrengung", "勉強"],
    ["N4", "強", "きょう・つよ", "stark", "勉強・強い"],
    ["N4", "旅", "りょ・たび", "Reise", "旅行"],
    ["N4", "館", "かん", "Gebäude / Halle", "図書館"],
    ["N4", "図", "ず・と", "Plan / Zeichnung", "地図"],
    ["N4", "館", "かん", "Halle / Gebäude", "映画館"],
    ["N4", "映", "えい・うつ", "projizieren", "映画"],
    ["N4", "画", "が・かく", "Bild", "映画"],
    ["N4", "音", "おん・おと", "Ton", "音楽"],
    ["N4", "楽", "がく・たの", "Musik / angenehm", "音楽・楽しい"],
    ["N4", "歌", "か・うた", "Lied", "歌う"],
    ["N4", "医", "い", "Medizin", "医者"],
    ["N4", "者", "しゃ・もの", "Person", "医者"],
    ["N4", "病", "びょう・や", "Krankheit", "病院"],
    ["N4", "院", "いん", "Institution", "病院"],
    ["N4", "薬", "やく・くすり", "Medizin", "薬"],
    ["N4", "体", "たい・からだ", "Körper", "体"],
    ["N4", "心", "しん・こころ", "Herz / Geist", "心配"],
    ["N4", "配", "はい・くば", "verteilen", "心配"],
    ["N4", "理", "り", "Grund / Logik", "理由"],
    ["N4", "由", "ゆ・よし", "Grund / Ursache", "理由"],
    ["N4", "計", "けい・はか", "messen / planen", "計画"],
    ["N4", "画", "が・かく", "Plan / Bild", "計画"],
    ["N4", "予", "よ", "vorher", "予定"],
    ["N4", "定", "てい・さだ", "festlegen", "予定"],
    ["N4", "約", "やく", "ungefähr / Versprechen", "予約"],
    ["N4", "連", "れん・つら", "verbinden", "連絡"],
    ["N4", "絡", "らく・から", "verwickeln", "連絡"],
    ["N4", "相", "そう・あい", "gegenseitig", "相談"],
    ["N4", "談", "だん", "Gespräch", "相談"],
    ["N4", "説", "せつ・と", "Erklärung", "説明"],
    ["N4", "明", "めい・あか", "hell / klar", "説明"],
    ["N4", "選", "せん・えら", "wählen", "選ぶ"],
    ["N4", "運", "うん・はこ", "transportieren / Glück", "運転"],
    ["N4", "転", "てん・ころ", "drehen", "運転"],
    ["N4", "空", "くう・そら", "leer / Himmel", "空港"],
    ["N4", "港", "こう・みなと", "Hafen", "空港"],
    ["N4", "発", "はつ", "Abfahrt / starten", "出発"],
    ["N4", "到", "とう", "ankommen", "到着"],
    ["N4", "着", "ちゃく・き", "ankommen / tragen", "到着"],
    ["N4", "住", "じゅう・す", "wohnen", "住所"],
    ["N4", "所", "しょ・ところ", "Ort", "住所"],
    ["N4", "場", "じょう・ば", "Ort", "場所"],
    ["N4", "所", "しょ・ところ", "Ort", "場所"],
    ["N4", "地", "ち・じ", "Erde / Gebiet", "地図"],
    ["N4", "図", "ず", "Karte / Plan", "地図"],
    ["N4", "京", "きょう", "Hauptstadt", "東京・京都"],
    ["N4", "県", "けん", "Präfektur", "県"],
    ["N4", "市", "し・いち", "Stadt / Markt", "市"],
    ["N4", "町", "ちょう・まち", "Stadt / Viertel", "町"],
    ["N4", "村", "そん・むら", "Dorf", "村"],
    ["N4", "区", "く", "Bezirk", "区"],
    ["N4", "都", "と・みやこ", "Metropole", "東京都"],
    ["N4", "府", "ふ", "Präfektur", "大阪府"],
    ["N4", "屋", "おく・や", "Haus / Laden", "屋上"],
    ["N4", "室", "しつ・むろ", "Zimmer", "教室"],
    ["N4", "階", "かい", "Stockwerk", "二階"],
    ["N4", "建", "けん・た", "bauen", "建物"],
    ["N4", "物", "ぶつ・もの", "Ding", "建物"],
    ["N4", "工", "こう", "Handwerk", "工場"],
    ["N4", "場", "じょう・ば", "Ort", "工場"],
    ["N4", "店", "てん・みせ", "Geschäft", "店員"],
    ["N4", "員", "いん", "Mitglied / Angestellte", "店員"],
    ["N4", "員", "いん", "Personal", "駅員"],
    ["N4", "員", "いん", "Mitglied", "会社員"],
    ["N4", "会", "かい", "Treffen / Firma", "会社"],
    ["N4", "社", "しゃ", "Firma", "会社"],
    ["N4", "仕", "し", "dienen", "仕事"],
    ["N4", "事", "じ・こと", "Sache", "仕事"],
    ["N4", "業", "ぎょう・わざ", "Beruf / Tätigkeit", "卒業"],
    ["N4", "卒", "そつ", "Abschluss", "卒業"],
    ["N4", "研", "けん・と", "schärfen / forschen", "研究"],
    ["N4", "究", "きゅう・きわ", "erforschen", "研究"],
    ["N4", "質", "しつ", "Qualität / Frage", "質問"],
    ["N4", "問", "もん・と", "Frage", "質問"],
    ["N4", "答", "とう・こた", "Antwort", "答え"],
    ["N4", "題", "だい", "Thema / Aufgabe", "問題"],
    ["N4", "問", "もん・と", "Frage", "問題"],
    ["N4", "試", "し・こころ", "versuchen / Prüfung", "試験"],
    ["N4", "験", "けん", "Erfahrung / Prüfung", "試験"],
    ["N4", "宿", "しゅく・やど", "Unterkunft", "宿題"],
    ["N4", "題", "だい", "Aufgabe", "宿題"],
    ["N4", "文", "ぶん・ふみ", "Text", "文章"],
    ["N4", "章", "しょう", "Kapitel", "文章"],
    ["N4", "字", "じ・あざ", "Zeichen", "漢字"],
    ["N4", "漢", "かん", "chinesisch", "漢字"],
    ["N4", "英", "えい", "englisch / hervorragend", "英語"],
    ["N4", "語", "ご・かた", "Sprache", "英語"],
    ["N4", "意", "い", "Absicht / Bedeutung", "意味"],
    ["N4", "味", "み・あじ", "Geschmack / Bedeutung", "意味"],
    ["N4", "発", "はつ", "Ausgabe / Start", "発音"],
    ["N4", "音", "おん・おと", "Ton", "発音"],
    ["N4", "読", "どく・よ", "lesen", "読書"],
    ["N4", "書", "しょ・か", "schreiben", "読書"],
    ["N4", "紙", "し・かみ", "Papier", "紙"],
    ["N4", "写", "しゃ・うつ", "kopieren", "写真"],
    ["N4", "真", "しん・ま", "wahr", "写真"],
    ["N4", "色", "しょく・いろ", "Farbe", "色"],
    ["N4", "赤", "せき・あか", "rot", "赤い"],
    ["N4", "青", "せい・あお", "blau", "青い"],
    ["N4", "白", "はく・しろ", "weiß", "白い"],
    ["N4", "黒", "こく・くろ", "schwarz", "黒い"],
    ["N4", "茶", "ちゃ", "Tee / braun", "お茶"],
    ["N4", "春", "しゅん・はる", "Frühling", "春"],
    ["N4", "夏", "か・なつ", "Sommer", "夏"],
    ["N4", "秋", "しゅう・あき", "Herbst", "秋"],
    ["N4", "冬", "とう・ふゆ", "Winter", "冬"],
    ["N4", "朝", "ちょう・あさ", "Morgen", "朝"],
    ["N4", "昼", "ちゅう・ひる", "Mittag", "昼"],
    ["N4", "夜", "や・よる", "Nacht", "夜"],
    ["N4", "夕", "せき・ゆう", "Abend", "夕方"],
    ["N4", "方", "ほう・かた", "Richtung / Person", "夕方"],
    ["N4", "曜", "よう", "Wochentag", "曜日"],
    ["N4", "週", "しゅう", "Woche", "一週間"],
    ["N4", "毎", "まい", "jede/r/s", "毎日"],
    ["N4", "去", "きょ・さ", "vergehen", "去年"],
    ["N4", "来", "らい・く", "kommen", "来年"],
    ["N4", "今", "こん・いま", "jetzt", "今年"],
    ["N4", "早", "そう・はや", "früh", "早い"],
    ["N4", "遅", "ち・おそ", "spät", "遅い"],
    ["N4", "近", "きん・ちか", "nah", "近い"],
    ["N4", "遠", "えん・とお", "weit", "遠い"],
    ["N4", "弱", "じゃく・よわ", "schwach", "弱い"],
    ["N4", "重", "じゅう・おも", "schwer", "重い"],
    ["N4", "軽", "けい・かる", "leicht", "軽い"],
    ["N4", "太", "たい・ふと", "dick", "太い"],
    ["N4", "細", "さい・ほそ", "dünn", "細い"],
    ["N4", "広", "こう・ひろ", "weit", "広い"],
    ["N4", "狭", "きょう・せま", "eng", "狭い"],
    ["N4", "悪", "あく・わる", "schlecht", "悪い"],
    ["N4", "特", "とく", "besonders", "特別"],
    ["N4", "別", "べつ・わか", "getrennt", "特別"],
    ["N4", "便", "べん・びん", "praktisch / Post", "便利"],
    ["N4", "利", "り", "Vorteil", "便利"],
    ["N4", "不", "ふ", "nicht", "不便"],
    ["N4", "切", "せつ・き", "schneiden / wichtig", "大切"],
    ["N4", "親", "しん・おや", "Eltern / vertraut", "親切"],
    ["N4", "急", "きゅう・いそ", "dringend", "急行"],
    ["N4", "通", "つう・とお", "durchgehen", "交通"],
    ["N4", "交", "こう・まじ", "Verkehr / Austausch", "交通"],
    ["N4", "道", "どう・みち", "Weg", "道路"],
    ["N4", "路", "ろ・じ", "Straße", "道路"],
    ["N4", "橋", "きょう・はし", "Brücke", "橋"],
    ["N4", "駐", "ちゅう", "parken", "駐車場"],
    ["N4", "車", "しゃ・くるま", "Fahrzeug", "駐車場"],
    ["N4", "荷", "か・に", "Gepäck", "荷物"],
    ["N4", "物", "ぶつ・もの", "Ding", "荷物"],
    ["N4", "旅", "りょ・たび", "Reise", "旅館"],
    ["N4", "館", "かん", "Gebäude", "旅館"],
    ["N4", "予", "よ", "vorher", "予約"],
    ["N4", "約", "やく", "Reservierung / ungefähr", "予約"],
    ["N4", "案", "あん", "Plan / Vorschlag", "案内"],
    ["N4", "内", "ない・うち", "innen", "案内"],
    ["N4", "世", "せい・よ", "Welt / Generation", "世界"],
    ["N4", "界", "かい", "Welt", "世界"],
    ["N4", "文", "ぶん・ふみ", "Kultur / Text", "文化"],
    ["N4", "化", "か・ば", "Veränderung", "文化"],
    ["N4", "歴", "れき", "Geschichte", "歴史"],
    ["N4", "史", "し", "Geschichte", "歴史"],
    ["N4", "政", "せい", "Politik", "政治"],
    ["N4", "治", "じ・おさ", "regieren / heilen", "政治"],
    ["N4", "経", "けい・へ", "durchgehen", "経済"],
    ["N4", "済", "さい・す", "beenden", "経済"],
    ["N4", "法", "ほう", "Gesetz / Methode", "法律"],
    ["N4", "律", "りつ", "Regel", "法律"],
    ["N4", "教", "きょう・おし", "Lehre", "教育"],
    ["N4", "育", "いく・そだ", "erziehen", "教育"],
    ["N4", "育", "いく・そだ", "aufziehen", "育てる"],
    ["N4", "産", "さん・う", "produzieren", "生産"],
    ["N4", "業", "ぎょう", "Industrie", "産業"],
    ["N4", "農", "のう", "Landwirtschaft", "農業"],
    ["N4", "貿", "ぼう", "Handel", "貿易"],
    ["N4", "易", "えき・やさ", "Handel / leicht", "貿易"],
    ["N4", "科", "か", "Fach / Wissenschaft", "科学"],
    ["N4", "学", "がく・まな", "lernen", "科学"],
    ["N4", "医", "い", "Medizin", "医学"],
    ["N4", "技", "ぎ・わざ", "Technik", "技術"],
    ["N4", "術", "じゅつ", "Kunst / Technik", "技術"],
    ["N4", "情", "じょう・なさ", "Gefühl / Information", "情報"],
    ["N4", "報", "ほう・むく", "Meldung", "情報"],
    ["N4", "新", "しん・あたら", "neu", "新聞"],
    ["N4", "聞", "ぶん・き", "hören", "新聞"],
    ["N4", "番", "ばん", "Nummer / Reihenfolge", "番号"],
    ["N4", "号", "ごう", "Nummer", "番号"],
    ["N4", "受", "じゅ・う", "empfangen", "受付"],
    ["N4", "付", "ふ・つ", "anhaften", "受付"],
    ["N4", "連", "れん", "verbinden", "連絡"],
    ["N4", "絡", "らく", "verwickeln", "連絡"],
    ["N4", "相", "そう", "gegenseitig", "相談"],
    ["N4", "談", "だん", "Gespräch", "相談"],
    ["N4", "注", "ちゅう・そそ", "Aufmerksamkeit", "注意"],
    ["N4", "意", "い", "Absicht", "注意"],
    ["N4", "危", "き・あぶ", "gefährlich", "危険"],
    ["N4", "険", "けん・けわ", "gefährlich", "危険"],
    ["N4", "安", "あん・やす", "sicher / billig", "安全"],
    ["N4", "全", "ぜん・まった", "ganz", "安全"],
    ["N4", "健", "けん・すこ", "gesund", "健康"],
    ["N4", "康", "こう", "gesund", "健康"],
    ["N4", "育", "いく・そだ", "erziehen", "教育"],
    ["N4", "活", "かつ・い", "Leben / aktiv", "生活"],
    ["N4", "生", "せい・い", "Leben", "生活"],
    ["N4", "慣", "かん・な", "gewöhnen", "慣れる"],
    ["N4", "残", "ざん・のこ", "übrig", "残る"],
    ["N4", "増", "ぞう・ふ", "zunehmen", "増える"],
    ["N4", "減", "げん・へ", "abnehmen", "減る"],
    ["N4", "比", "ひ・くら", "vergleichen", "比べる"],
    ["N4", "較", "かく", "vergleichen", "比較"],
    ["N4", "選", "せん・えら", "auswählen", "選ぶ"],
    ["N4", "決", "けつ・き", "entscheiden", "決める"],
    ["N4", "必", "ひつ・かなら", "unbedingt", "必要"],
    ["N4", "要", "よう・い", "notwendig", "必要"],
    ["N4", "準", "じゅん", "Standard / Vorbereitung", "準備"],
    ["N4", "備", "び・そな", "vorbereiten", "準備"]
  ];

  const VERBS = [
    {dict:"食べる",type:"Ichidan",meaning:"essen",masu:"食べます",negative:"食べない",past:"食べた",te:"食べて",potential:"食べられる"},
    {dict:"見る",type:"Ichidan",meaning:"sehen",masu:"見ます",negative:"見ない",past:"見た",te:"見て",potential:"見られる"},
    {dict:"行く",type:"Godan",meaning:"gehen",masu:"行きます",negative:"行かない",past:"行った",te:"行って",potential:"行ける"},
    {dict:"書く",type:"Godan",meaning:"schreiben",masu:"書きます",negative:"書かない",past:"書いた",te:"書いて",potential:"書ける"},
    {dict:"読む",type:"Godan",meaning:"lesen",masu:"読みます",negative:"読まない",past:"読んだ",te:"読んで",potential:"読める"},
    {dict:"話す",type:"Godan",meaning:"sprechen",masu:"話します",negative:"話さない",past:"話した",te:"話して",potential:"話せる"},
    {dict:"する",type:"unregelmäßig",meaning:"machen",masu:"します",negative:"しない",past:"した",te:"して",potential:"できる"},
    {dict:"来る",type:"unregelmäßig",meaning:"kommen",masu:"来ます",negative:"来ない",past:"来た",te:"来て",potential:"来られる"}
  ];

  const COUNTERS = [
    ["人","にん","Menschen","一人 ひとり・二人 ふたり・三人 さんにん"],
    ["本","ほん","lange zylindrische Dinge","一本 いっぽん・三本 さんぼん・六本 ろっぽん"],
    ["枚","まい","flache Dinge","一枚 いちまい・三枚 さんまい"],
    ["匹","ひき","kleine Tiere","一匹 いっぴき・三匹 さんびき・六匹 ろっぴき"],
    ["台","だい","Maschinen/Fahrzeuge","一台 いちだい・二台 にだい"],
    ["回","かい","Male / Wiederholungen","一回 いっかい・三回 さんかい"],
    ["冊","さつ","gebundene Bücher","一冊 いっさつ・八冊 はっさつ"],
    ["個","こ","kleine Gegenstände","一個 いっこ・六個 ろっこ"]
  ];

  const CONFUSIONS = [
    ["ぬ","め","Hiragana"],["れ","ね","Hiragana"],["さ","き","Hiragana"],["シ","ツ","Katakana"],
    ["ソ","ン","Katakana"],["ク","ケ","Katakana"],["フ","ワ","Katakana"],["ロ","口","Katakana/Kanji"],
    {"id": "n4-01", "level": "N4", "title": "～ながら", "summary": "Zwei Handlungen gleichzeitig", "explanation": "Die ます-Stammform + ながら verbindet zwei gleichzeitig ausgeführte Handlungen. Die wichtigere Handlung steht meist am Satzende.", "examples": [["音楽を聞きながら勉強します。", "Ich lerne, während ich Musik höre."], ["歩きながら話しました。", "Wir haben gesprochen, während wir gingen."]], "tip": "Das Subjekt beider Handlungen ist normalerweise gleich."},
    {"id": "n4-02", "level": "N4", "title": "～たことがある", "summary": "Erfahrungen ausdrücken", "explanation": "Verb in た-Form + ことがある bedeutet, etwas schon einmal erlebt oder getan zu haben.", "examples": [["日本へ行ったことがあります。", "Ich war schon einmal in Japan."], ["納豆を食べたことがありません。", "Ich habe noch nie Natto gegessen."]], "tip": "Für ein konkretes Ereignis gestern etc. verwendet man die normale Vergangenheit, nicht dieses Muster."},
    {"id": "n4-03", "level": "N4", "title": "～たり～たりする", "summary": "Beispiele von Handlungen nennen", "explanation": "Mit たり-Formen nennt man beispielhaft mehrere Aktivitäten, ohne eine vollständige Liste zu behaupten.", "examples": [["本を読んだり映画を見たりします。", "Ich lese unter anderem Bücher und schaue Filme."], ["週末は掃除したり買い物したりしました。", "Am Wochenende habe ich unter anderem geputzt und eingekauft."]], "tip": "Am Ende steht する bzw. eine konjugierte Form davon."},
    {"id": "n4-04", "level": "N4", "title": "～なければならない", "summary": "Pflicht und Notwendigkeit", "explanation": "Die negative ない-Form wird zu ～なければならない: etwas muss getan werden.", "examples": [["薬を飲まなければなりません。", "Ich muss Medizin nehmen."], ["明日早く起きなければなりません。", "Ich muss morgen früh aufstehen."]], "tip": "Im Gespräch hört man oft kürzere Varianten wie ～なきゃ."},
    {"id": "n4-05", "level": "N4", "title": "～なくてもいい", "summary": "Etwas nicht tun müssen", "explanation": "Die ない-Form + なくてもいい bedeutet, dass etwas nicht notwendig ist.", "examples": [["明日は来なくてもいいです。", "Du musst morgen nicht kommen."], ["全部食べなくてもいいです。", "Du musst nicht alles essen."]], "tip": "Nicht mit ～てはいけない verwechseln: Das bedeutet 'nicht dürfen'."},
    {"id": "n4-06", "level": "N4", "title": "～かもしれない", "summary": "Möglichkeit ausdrücken", "explanation": "～かもしれない bedeutet 'vielleicht / möglicherweise'. Es zeigt geringere Sicherheit als でしょう.", "examples": [["午後は雨かもしれません。", "Vielleicht regnet es am Nachmittag."], ["彼は来ないかもしれません。", "Vielleicht kommt er nicht."]], "tip": "Höflich: ～かもしれません."},
    {"id": "n4-07", "level": "N4", "title": "～でしょう", "summary": "Vermutung und Bestätigung", "explanation": "でしょう drückt eine relativ wahrscheinliche Vermutung aus oder bittet um Bestätigung.", "examples": [["明日は寒いでしょう。", "Morgen wird es wahrscheinlich kalt."], ["これは田中さんの本でしょう。", "Das ist doch Tanakas Buch, oder?"]], "tip": "Im lockeren Stil: だろう."},
    {"id": "n4-08", "level": "N4", "title": "～そうだ", "summary": "Anschein und Hörensagen", "explanation": "そうだ kann je nach Anschluss entweder 'sieht so aus' oder 'ich habe gehört, dass' bedeuten.", "examples": [["雨が降りそうです。", "Es sieht nach Regen aus."], ["田中さんは休むそうです。", "Ich habe gehört, dass Tanaka frei nimmt."]], "tip": "Die Form vor そう ist je nach Bedeutung unterschiedlich."},
    {"id": "n4-09", "level": "N4", "title": "～つもりだ", "summary": "Absichten ausdrücken", "explanation": "Wörterbuchform + つもりだ bedeutet, dass man fest beabsichtigt, etwas zu tun.", "examples": [["来年留学するつもりです。", "Ich habe vor, nächstes Jahr im Ausland zu studieren."], ["今日は出かけないつもりです。", "Ich habe vor, heute nicht auszugehen."]], "tip": "Stärker als ein spontaner Gedanke."},
    {"id": "n4-10", "level": "N4", "title": "～予定だ", "summary": "Geplante Ereignisse", "explanation": "予定だ beschreibt einen Plan oder Termin, der bereits festgelegt ist.", "examples": [["来月引っ越す予定です。", "Ich plane, nächsten Monat umzuziehen."], ["会議は三時に始まる予定です。", "Die Besprechung soll um drei beginnen."]], "tip": "Für persönliche Absicht passt つもり oft besser."},
    {"id": "n4-11", "level": "N4", "title": "～ほうがいい", "summary": "Rat geben", "explanation": "Vergangenheit + ほうがいい empfiehlt eine Handlung; negative ない-Form + ほうがいい rät davon ab.", "examples": [["早く寝たほうがいいです。", "Du solltest besser früh schlafen gehen."], ["無理をしないほうがいいです。", "Du solltest dich nicht überfordern."]], "tip": "Es ist ein relativ direkter Rat."},
    {"id": "n4-12", "level": "N4", "title": "～すぎる", "summary": "Zu viel / zu sehr", "explanation": "Verbstamm oder Adjektivstamm + すぎる bedeutet, dass etwas übermäßig ist.", "examples": [["食べすぎました。", "Ich habe zu viel gegessen."], ["このかばんは高すぎます。", "Diese Tasche ist zu teuer."]], "tip": "Bei い-Adjektiven fällt das い weg: 高い → 高すぎる."},
    {"id": "n4-13", "level": "N4", "title": "～やすい / ～にくい", "summary": "Leicht oder schwer zu tun", "explanation": "Verbstamm + やすい bzw. にくい beschreibt, wie leicht oder schwer eine Handlung ist.", "examples": [["この本は読みやすいです。", "Dieses Buch ist leicht zu lesen."], ["この漢字は覚えにくいです。", "Dieses Kanji ist schwer zu merken."]], "tip": "Beide verhalten sich wie い-Adjektive."},
    {"id": "n4-14", "level": "N4", "title": "～てみる", "summary": "Etwas ausprobieren", "explanation": "て-Form + みる bedeutet, eine Handlung probeweise zu versuchen.", "examples": [["この料理を食べてみます。", "Ich probiere dieses Gericht."], ["日本語で話してみてください。", "Versuchen Sie bitte, auf Japanisch zu sprechen."]], "tip": "Nicht wörtlich als 'sehen' übersetzen."},
    {"id": "n4-15", "level": "N4", "title": "～ておく", "summary": "Vorbereitung im Voraus", "explanation": "て-Form + おく bedeutet, etwas vorbereitend oder vorsorglich zu tun.", "examples": [["ホテルを予約しておきます。", "Ich reserviere das Hotel im Voraus."], ["資料を読んでおいてください。", "Bitte lesen Sie die Unterlagen vorher."]], "tip": "Umgangssprachlich oft ～とく."},
    {"id": "n4-16", "level": "N4", "title": "～てしまう", "summary": "Abschluss oder Bedauern", "explanation": "て-Form + しまう kann ausdrücken, dass etwas vollständig abgeschlossen wird oder leider passiert ist.", "examples": [["宿題を全部してしまいました。", "Ich habe die Hausaufgaben komplett erledigt."], ["財布を忘れてしまいました。", "Ich habe leider mein Portemonnaie vergessen."]], "tip": "Umgangssprachlich oft ～ちゃう / ～じゃう."},
    {"id": "n4-17", "level": "N4", "title": "～てある", "summary": "Absichtlich hergestellter Zustand", "explanation": "Transitiver Verb in て-Form + ある beschreibt einen Zustand als Ergebnis einer absichtlichen Handlung.", "examples": [["窓が開けてあります。", "Das Fenster wurde absichtlich geöffnet."], ["名前が書いてあります。", "Der Name steht dort geschrieben."]], "tip": "Fokus liegt auf dem vorhandenen Ergebnis."},
    {"id": "n4-18", "level": "N4", "title": "～ところだ", "summary": "Zeitpunkt einer Handlung", "explanation": "Wörterbuchform, ている oder た + ところだ unterscheiden 'gerade im Begriff', 'gerade dabei' und 'gerade getan'.", "examples": [["今から食べるところです。", "Ich bin gerade im Begriff zu essen."], ["今食べているところです。", "Ich esse gerade."]], "tip": "Mit た: 今食べたところです = Ich habe gerade gegessen."},
    {"id": "n4-19", "level": "N4", "title": "～ようになる", "summary": "Veränderung einer Fähigkeit oder Gewohnheit", "explanation": "～ようになる beschreibt, dass etwas im Laufe der Zeit möglich oder üblich wird.", "examples": [["日本語が話せるようになりました。", "Ich kann inzwischen Japanisch sprechen."], ["早く起きるようになりました。", "Ich stehe inzwischen früh auf."]], "tip": "Es geht um eine Veränderung des Zustands."},
    {"id": "n4-20", "level": "N4", "title": "～ようにする", "summary": "Bewusst auf etwas achten", "explanation": "～ようにする beschreibt eine bewusste Bemühung oder Gewohnheit.", "examples": [["毎日歩くようにしています。", "Ich achte darauf, täglich zu gehen."], ["夜遅く食べないようにしています。", "Ich versuche, nachts nicht spät zu essen."]], "tip": "Vergleiche ようになる: dort geschieht die Veränderung eher als Ergebnis."},
    {"id": "n4-21", "level": "N4", "title": "～ので / ～のに", "summary": "Grund und Gegensatz", "explanation": "ので gibt einen Grund höflicher/weicher an; のに drückt einen unerwarteten Gegensatz aus.", "examples": [["雨なので出かけません。", "Weil es regnet, gehe ich nicht aus."], ["勉強したのに忘れました。", "Obwohl ich gelernt habe, habe ich es vergessen."]], "tip": "ので klingt oft sachlicher als から."},
    {"id": "n4-22", "level": "N4", "title": "～し", "summary": "Mehrere Gründe oder Eigenschaften", "explanation": "し verbindet mehrere Gründe oder Merkmale und lässt oft offen, dass es noch weitere gibt.", "examples": [["安いし、おいしいです。", "Es ist günstig und außerdem lecker."], ["駅も近いし、便利です。", "Der Bahnhof ist nah und es ist praktisch."]], "tip": "Sehr nützlich für Begründungen."},
    {"id": "n4-23", "level": "N4", "title": "～なら", "summary": "Themenbezogene Bedingung", "explanation": "なら bedeutet ungefähr 'wenn es um X geht / falls X der Fall ist'.", "examples": [["京都なら春がおすすめです。", "Wenn es um Kyoto geht, empfehle ich den Frühling."], ["時間がないなら、明日にしましょう。", "Wenn du keine Zeit hast, machen wir es morgen."]], "tip": "Oft reagiert なら auf Information aus dem vorherigen Gespräch."},
    {"id": "n4-24", "level": "N4", "title": "～たら", "summary": "Flexible Bedingung", "explanation": "たら kann 'wenn', 'falls' oder 'nachdem' bedeuten.", "examples": [["家に帰ったら電話します。", "Wenn ich zu Hause bin, rufe ich an."], ["雨だったら行きません。", "Wenn es regnet, gehe ich nicht."]], "tip": "Sehr vielseitig und im Alltag häufig."},
    {"id": "n4-25", "level": "N4", "title": "～ば", "summary": "Bedingung", "explanation": "Die ば-Form drückt eine Bedingung aus: wenn X, dann Y.", "examples": [["時間があれば行きます。", "Wenn ich Zeit habe, gehe ich."], ["安ければ買います。", "Wenn es günstig ist, kaufe ich es."]], "tip": "Die Bildung unterscheidet sich bei Verben und Adjektiven."},
    {"id": "n4-26", "level": "N4", "title": "～と", "summary": "Automatische Folge", "explanation": "Konditionales と wird für natürliche, automatische oder wiederkehrende Folgen verwendet.", "examples": [["春になると暖かくなります。", "Wenn Frühling wird, wird es warm."], ["このボタンを押すとドアが開きます。", "Wenn man diesen Knopf drückt, öffnet sich die Tür."]], "tip": "Nicht ideal für persönliche Willensentscheidungen im Folgesatz."},
    {"id": "n4-27", "level": "N4", "title": "～ても", "summary": "Auch wenn", "explanation": "て-Form + も bedeutet, dass der Folgesatz trotz der Bedingung gilt.", "examples": [["雨が降っても行きます。", "Auch wenn es regnet, gehe ich."], ["高くても買いたいです。", "Auch wenn es teuer ist, möchte ich es kaufen."]], "tip": "Adjektive und Nomen haben eigene Anschlussformen."},
    {"id": "n4-28", "level": "N4", "title": "～しか～ない", "summary": "Nur / nichts außer", "explanation": "しか steht mit einer negativen Verbform und bedeutet 'nur'.", "examples": [["千円しかありません。", "Ich habe nur 1000 Yen."], ["一人しか来ませんでした。", "Nur eine Person kam."]], "tip": "Obwohl die Bedeutung positiv wirkt, ist das Verb negativ."},
    {"id": "n4-29", "level": "N4", "title": "～について", "summary": "Über ein Thema", "explanation": "Nomen + について bedeutet 'über / bezüglich'.", "examples": [["日本文化について勉強します。", "Ich lerne über japanische Kultur."], ["この問題について話しましょう。", "Lass uns über dieses Problem sprechen."]], "tip": "In formelleren Texten sehr häufig."},
    {"id": "n4-30", "level": "N4", "title": "～によると", "summary": "Quelle einer Information", "explanation": "Nomen + によると bedeutet 'laut / gemäß'.", "examples": [["天気予報によると、明日は雨です。", "Laut Wetterbericht regnet es morgen."], ["ニュースによると、電車が遅れています。", "Laut Nachrichten hat der Zug Verspätung."]], "tip": "Danach steht häufig そうだ oder eine andere Informationsform."},
    {"id": "n4-31", "level": "N4", "title": "～までに", "summary": "Frist", "explanation": "までに bedeutet 'bis spätestens zu einem Zeitpunkt'.", "examples": [["五時までに帰ってください。", "Bitte kommen Sie bis fünf Uhr zurück."], ["金曜日までに出してください。", "Bitte geben Sie es bis Freitag ab."]], "tip": "まで = bis andauernd; までに = spätestens bis."},
    {"id": "n4-32", "level": "N4", "title": "～間に", "summary": "Während eines Zeitraums", "explanation": "間に markiert eine Handlung, die innerhalb eines Zeitraums stattfindet.", "examples": [["子どもが寝ている間に勉強します。", "Ich lerne, während das Kind schläft."], ["日本にいる間に京都へ行きたいです。", "Während ich in Japan bin, möchte ich nach Kyoto."]], "tip": "間 ohne に betont eher die gesamte Dauer."},
    {"id": "n4-33", "level": "N4", "title": "～ために", "summary": "Zweck", "explanation": "Wörterbuchform + ために beschreibt einen Zweck. Auch Nomen + のために ist möglich.", "examples": [["日本で働くために勉強しています。", "Ich lerne, um in Japan zu arbeiten."], ["健康のために歩きます。", "Ich gehe meiner Gesundheit zuliebe spazieren."]], "tip": "Für Fähigkeiten oder unbeabsichtigte Ergebnisse wird oft ように verwendet."},
    {"id": "n4-34", "level": "N4", "title": "～方", "summary": "Wie man etwas tut", "explanation": "Verbstamm + 方 bedeutet 'Art und Weise, etwas zu tun'.", "examples": [["使い方を教えてください。", "Bitte zeigen Sie mir, wie man es benutzt."], ["漢字の読み方が分かりません。", "Ich kenne die Lesung des Kanji nicht."]], "tip": "方 wird hier かた gelesen."},
    {"id": "n4-35", "level": "N4", "title": "～かどうか", "summary": "Ob oder nicht", "explanation": "～かどうか bettet eine Ja/Nein-Frage in einen größeren Satz ein.", "examples": [["行くかどうかまだ決めていません。", "Ich habe noch nicht entschieden, ob ich gehe."], ["開いているかどうか確認します。", "Ich prüfe, ob es geöffnet ist."]], "tip": "Bei Fragewörtern verwendet man direkt Fragewort + か."}
  ];

  const buildCards = () => {
    const cards = [];
    HIRAGANA.forEach(([j,r],i)=>cards.push({id:`h-${i}`,deck:"Hiragana",level:"Kana",front:j,reading:r,meaning:r,example:`Laut: ${r}`,exampleDe:""}));
    KATAKANA.forEach(([j,r],i)=>cards.push({id:`k-${i}`,deck:"Katakana",level:"Kana",front:j,reading:r,meaning:r,example:`Laut: ${r}`,exampleDe:""}));
    VOCAB.forEach((x,i)=>cards.push({id:`v-${i}`,deck:"Vokabeln",level:x[0],front:x[1],reading:x[2],meaning:x[3],example:x[4],exampleDe:x[5]}));
    GRAMMAR.forEach((x,i)=>cards.push({id:`g-${i}`,deck:"Grammatik",level:x[0],front:x[1],reading:x[2],meaning:x[3],example:x[4],exampleDe:x[5]}));
    KANJI.forEach((x,i)=>cards.push({id:`j-${i}`,deck:"Kanji",level:x[0],front:x[1],reading:x[2],meaning:x[3],example:x[4],exampleDe:""}));
    return cards;
  };

  return {HIRAGANA,KATAKANA,VOCAB,GRAMMAR,KANJI,VERBS,COUNTERS,CONFUSIONS,LESSONS,buildCards};
})();
